z
Signed-off-by: viet.ngovan <viet.ngovanviet@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -345,7 +345,7 @@ jobs:
       # Checkout code from git
       - checkout
       - install_awscli
-      - revert-migrations-force
+      # - revert-migrations-force
       - run:
           name: Run migrations
           command: |
@@ -475,30 +475,25 @@ jobs:
       - destroy-environment
       - revert-migrations
 
+  # -c − This creates an archive file.
 
+  # -x − The option extracts the archive file.
 
-# -c − This creates an archive file.
+  # -f − Specifies the filename of the archive file.
 
-# -x − The option extracts the archive file.
+  # -v − This prints verbose information for any tar operation on the terminal.
 
-# -f − Specifies the filename of the archive file.
+  # -t − This lists all the files inside an archive file.
 
-# -v − This prints verbose information for any tar operation on the terminal.
+  # -u − This archives a file and then adds it to an existing archive file.
 
-# -t − This lists all the files inside an archive file.
+  # -r − This updates a file or directory located inside a .tar file
 
-# -u − This archives a file and then adds it to an existing archive file.
+  # -z − Creates a tar file using gzip compression
 
-# -r − This updates a file or directory located inside a .tar file
+  # -j − Create an archive file using the bzip2 compression
 
-# -z − Creates a tar file using gzip compression
-
-# -j − Create an archive file using the bzip2 compression
-
-# -W − The -w option verifies an archive file.
-
-
-
+  # -W − The -w option verifies an archive file.
 
   smoke-test:
     docker:
@@ -528,28 +523,28 @@ jobs:
             FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
             if curl -s $FRONTEND_WEBSITE | grep "Welcome"
             then
-              exit 0
+              exit 1
             else
               exit 1
             fi
       - destroy-environment
       - revert-migrations
-#  Here's where you will add some code to rollback on failure
+  #  Here's where you will add some code to rollback on failure
 
-#   cloudfront-update:
-#     docker:
-#       # Docker image here that supports AWS CLI
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Update cloudfront distribution
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure
+  #   cloudfront-update:
+  #     docker:
+  #       # Docker image here that supports AWS CLI
+  #     steps:
+  #       # Checkout code from git
+  #       - run:
+  #           name: Install dependencies
+  #           command: |
+  #             # your code here
+  #       - run:
+  #           name: Update cloudfront distribution
+  #           command: |
+  #             # your code here
+  #       # Here's where you will add some code to rollback on failure
 
   cloudfront-update:
     docker:
@@ -566,7 +561,7 @@ jobs:
             echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
 
             curl https://kvdb.io/CALzhBUmmPzdTRrQYKNfEh/old_workflow_id -d "${OLD_WORKFLOW_ID}"
-                
+
       - run:
           name: Update cloudfront distribution
           command: |
@@ -578,24 +573,24 @@ jobs:
       - destroy-environment
       - revert-migrations
 
-# cleanup:
-#     docker:
-#       # Docker image here
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Get old stack workflow id
-#           command: |
-#             # your code here
-#             export OldWorkflowID="the id here"
-#             export STACKS=[] #put the list of stacks here
-#       - run:
-#           name: Remove old stacks and files
-#           command: |
-#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-#             then
-#               # your code here
-#             fi
+  # cleanup:
+  #     docker:
+  #       # Docker image here
+  #     steps:
+  #       # Checkout code from git
+  #       - run:
+  #           name: Get old stack workflow id
+  #           command: |
+  #             # your code here
+  #             export OldWorkflowID="the id here"
+  #             export STACKS=[] #put the list of stacks here
+  #       - run:
+  #           name: Remove old stacks and files
+  #           command: |
+  #             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+  #             then
+  #               # your code here
+  #             fi
   cleanup:
     docker:
       - image: amazon/aws-cli
@@ -617,7 +612,6 @@ jobs:
               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
             fi
-
 
   add-prometheus-node-exporter:
     docker:
@@ -642,8 +636,6 @@ jobs:
 
       - destroy-environment
       - revert-migrations
-
-
 
 workflows:
   default:
@@ -676,11 +668,10 @@ workflows:
           requires: [run-migrations]
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
-
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
 
       #  Slack configuraition
   # send-notification:
