z
Signed-off-by: viet.ngovan <viet.ngovanviet@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -49,7 +49,7 @@ commands:
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     # parameters:
-      # Add parameter here
+    # Add parameter here
     steps:
       - run:
           name: Revert migrations
@@ -66,27 +66,27 @@ commands:
               npm run migrations:revert
               # exit 1
             fi
- 
+
   revert-migrations-force:
-      description: Revert the last migration if successfully run in the current workflow.
-      # parameters:
-        # Add parameter here
-      steps:
-        - run:
-            name: Revert migrations
-            # Add when this will run
-            # when: on_fail
-            command: |
-              # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-              SUCCESS=$(curl https://kvdb.io/CALzhBUmmPzdTRrQYKNfEh/migration_${CIRCLE_WORKFLOW_ID:0:7})
-              if(( $SUCCESS==${CIRCLE_WORKFLOW_ID:0:7} ));
-              then
-                cd ~/project/backend
-                npm install
-              #  Add revert code here. You can find this in the Getting Started section.
-                npm run migrations:revert
-                # exit 1
-              fi
+    description: Revert the last migration if successfully run in the current workflow.
+    # parameters:
+    # Add parameter here
+    steps:
+      - run:
+          name: Revert migrations
+          # Add when this will run
+          # when: on_fail
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS=$(curl https://kvdb.io/CALzhBUmmPzdTRrQYKNfEh/migration_${CIRCLE_WORKFLOW_ID:0:7})
+            if(( $SUCCESS==${CIRCLE_WORKFLOW_ID:0:7} ));
+            then
+              cd ~/project/backend
+              npm install
+            #  Add revert code here. You can find this in the Getting Started section.
+              npm run migrations:revert
+              # exit 1
+            fi
 
   install_nodejs:
     description: Install Node.js 13
@@ -113,7 +113,7 @@ jobs:
       #     event: fail
       #     mentions: <@U8XXXXXXX>, @UserName
       #     template: basic_fail_1
-  
+
   build-frontend:
     docker:
       - image: circleci/node:13.8.0
@@ -314,7 +314,7 @@ jobs:
       # Checkout code from git
       - checkout
       # install dependence
-        # cli
+      # cli
       - install_awscli
         # ansible
       - install_ansible
@@ -370,7 +370,7 @@ jobs:
 
             npm install
             ## Run and save the migration output
-            
+
             npm run migrations > migrations_dump.txt
             cat migrations_dump.txt
             # exit 1
@@ -385,7 +385,7 @@ jobs:
                 -d ${CIRCLE_WORKFLOW_ID:0:7}
               fi
             # exit 1
-     # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure
       - destroy-environment
       - revert-migrations
 
@@ -430,7 +430,7 @@ jobs:
       # Here's where you will add some code to rollback on failure
       - destroy-environment
       - revert-migrations
-  
+
   deploy-backend:
     docker:
       - image: cimg/base:stable
@@ -452,7 +452,7 @@ jobs:
       - attach_workspace:
           at: ~/
       # - restore_cache:
-      #     keys: [backend-build]    
+      #     keys: [backend-build]
       - run:
           name: Install dependencies
           command: |
@@ -467,13 +467,13 @@ jobs:
             cd ..
 
             tar -C backend -czvf artifact.tar.gz .
-            cp artifact.tar.gz .circleci/ansible/roles/deploy/files
+            # cp artifact.tar.gz .circleci/ansible/roles/deploy/files 
 
             cd .circleci/ansible
             echo "Contents  of the inventory.txt file is -------"
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
-      
+
       # Here's where you will add some code to rollback on failure
       # - destroy-environment
       # - revert-migrations
@@ -559,8 +559,8 @@ workflows:
       # - run-migrations:
       #     requires: [configure-infrastructure]
       # - deploy-frontend:
-          # requires: [run-migrations]
-          # requires: [configure-infrastructure]
+      # requires: [run-migrations]
+      # requires: [configure-infrastructure]
       - deploy-backend:
           # requires: [run-migrations]
           requires: [configure-infrastructure]
